# Disable entire database wipe instructions preventing catastrophic human logic errors
rename-command FLUSHALL ""
rename-command FLUSHDB ""

# Enable physical snapshots bounding RAM to Disk preventing IO data loss
appendonly yes
appendfsync everysec

# Memory Policy
maxmemory 512mb
maxmemory-policy allkeys-lru

# Disable protected mode since we rely strictly on Docker network segregation
protected-mode no
