global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'slack-notifications'

receivers:
  - name: 'slack-notifications'
    # Define Slack/Discord webhooks natively here via environments typically
    webhook_configs:
      - url: 'http://localhost:3000/mock/slack'
