-- Migration 004: Alerts Table
-- Stores threat detections and policy violations generated by Phase 1 detection modules.

CREATE TABLE IF NOT EXISTS alerts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    event_id UUID REFERENCES events(id) ON DELETE SET NULL, -- Nullable for multi-event correlation alerts
    type VARCHAR(100) NOT NULL, -- e.g., 'rapid_failed_login', 'impossible_travel'
    severity VARCHAR(20) NOT NULL, -- 'low', 'medium', 'high', 'critical'
    status VARCHAR(20) NOT NULL DEFAULT 'open', -- 'open', 'investigating', 'resolved', 'false_positive'
    metadata JSONB, -- Detection module specific context and evidence
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP WITH TIME ZONE
);

-- Fast retrieval of recent alerts per tenant
CREATE INDEX IF NOT EXISTS idx_alerts_org_created ON alerts(organization_id, created_at DESC);

-- Fast retrieval of active/severe alerts per tenant
CREATE INDEX IF NOT EXISTS idx_alerts_org_severity_status ON alerts(organization_id, severity, status);
