import { FastifyRequest, FastifyReply } from 'fastify';
import { z } from 'zod';
import { redisClient } from '../lib/redis.js';
import { detectionEngine } from '../detection/engine.js';
import { DetectionEvent, DetectionContext } from '../detection/types.js';
import { randomUUID } from 'crypto';
import { MetricsService } from '../services/metrics.service.js';
import { performance } from 'perf_hooks';

const evaluateSchema = z.object({
    event_type: z.string().default('pre_authentication'),
    ip_address: z.string().ip().optional(),
    email: z.string().email().optional(),
    user_agent: z.string().optional(),
    device_id: z.string().optional(),
    payload: z.record(z.unknown()).optional().default({})
});

export class EvaluateController {
    /**
     * POST /api/v1/evaluate
     * Synchronous Inline Risk Evaluation Endpoint.
     * Protected apps call this BEFORE authenticating the user to get a real-time policy decision.
     */
    static async evaluate(request: FastifyRequest, reply: FastifyReply) {
        const start = performance.now();
        const validation = evaluateSchema.safeParse(request.body);
        
        if (!validation.success) {
            return reply.code(400).send({
                error: 'Bad Request',
                details: validation.error.format(),
            });
        }

        const data = validation.data;
        const orgId = request.orgId;
        const entity = data.email || data.ip_address || 'unknown';

        // 1. Build a synthetic DetectionEvent for the engine
        const eventId = randomUUID();
        const detectionEvent: DetectionEvent = {
            id: eventId,
            type: data.event_type,
            timestamp: Date.now(),
            ...(data.ip_address && { ip: data.ip_address }),
            ...(data.email && { email: data.email }),
            ...(data.device_id && { device: data.device_id }),
            ...(data.user_agent && { userAgent: data.user_agent }),
            payload: {
                ...data.payload,
                ip_address: data.ip_address,
                email: data.email,
                device_id: data.device_id,
                user_agent: data.user_agent
            }
        };

        const context: DetectionContext = {
            orgId,
            redis: redisClient
        };

        // 2. Synchronously execute the detection engine (runs heuristics immediately)
        // Note: The engine handles its own error catching per rule so it won't throw
        await detectionEngine.execute(detectionEvent, context);

        // 3. Read the real-time aggregated risk score generated by the engine
        // We must check BOTH the IP entity and the Email entity, taking the highest risk
        const riskKeyEmail = data.email ? `risk:account:${orgId}:${data.email}` : null;
        const riskKeyIp = data.ip_address ? `risk:account:${orgId}:${data.ip_address}` : null;
        
        let maxRiskScore = 0;
        
        if (riskKeyEmail || riskKeyIp) {
            const pipeline = redisClient.pipeline();
            if (riskKeyEmail) pipeline.get(riskKeyEmail);
            if (riskKeyIp) pipeline.get(riskKeyIp);
            
            const results = await pipeline.exec();
            if (results) {
                for (const res of results) {
                    const score = parseInt((res[1] as string) || '0', 10);
                    if (score > maxRiskScore) maxRiskScore = score;
                }
            }
        }

        // Evaluate intrinsic risk as a baseline if engine risk is 0
        const { RiskAssessmentService } = await import('../services/risk.service.js');
        const intrinsicRisk = RiskAssessmentService.evaluate({ type: data.event_type, payload: detectionEvent.payload });
        
        const finalRisk = Math.max(maxRiskScore, intrinsicRisk);

        // 4. Policy Decision Matrix
        let action = 'allow';
        let reason = 'Risk within acceptable thresholds';

        if (finalRisk >= 80) {
            action = 'block';
            reason = 'Critical risk threshold exceeded (Inline Enforcement)';
            // Log active intervention
            try {
                const { EventService } = await import('../services/event.service.js');
                await EventService.publish({
                    organization_id: orgId,
                    event_type: 'PRE_AUTH_BLOCKED',
                    payload: { entity, original_event: data.event_type, risk_score: finalRisk, ip: data.ip_address }
                });
            } catch (e) { /* background best effort */ }
        } else if (finalRisk >= 40) {
            action = 'challenge_mfa';
            reason = 'Elevated risk detected. Step-up authentication required.';
        }

        const durationInMs = performance.now() - start;

        // Return the crisp decision back to the Identity Provider
        return reply.code(200).send({
            action,
            risk_score: finalRisk,
            reason,
            latency_ms: Math.round(durationInMs),
            event_id: eventId
        });
    }
}
